spring.datasource.url=${DB_URL:jdbc:h2:file:./server/data/cloud;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
server.port=${PORT:8080}
server.error.include-message=never
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-null-for-primitives=true
server.tomcat.max-http-form-post-size=128KB
