package com.shipgame.nanhai;

import com.badlogic.gdx.Game;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.shipgame.nanhai.data.AccountStore;
import com.shipgame.nanhai.data.GameState;
import com.shipgame.nanhai.screen.LoginScreen;
import com.shipgame.nanhai.ui.UiFactory;
import com.shipgame.nanhai.ui.UpdateChecker;

public class NanHaiVoyage extends Game {

    public SpriteBatch batch;
    public BitmapFont font;
    public BitmapFont fontSmall;
    public Skin skin;
    public AccountStore accounts;
    public String currentUser;
    public GameState state;
    /** Backend-provided update checker (Android: GitHub Releases). Null on desktop. */
    public UpdateChecker updateChecker;

    @Override
    public void create() {
        installCrashLogger();
        batch = new SpriteBatch();
        font = loadFont(22);
        fontSmall = loadFont(16);
        skin = UiFactory.create(font, fontSmall);
        accounts = new AccountStore();
        setScreen(new LoginScreen(this));
    }

    /**
     * Writes every uncaught throwable to internal storage (crash-log.txt) so a
     * phone crash can be diagnosed without adb. Falls back silently if the
     * write itself fails.
     */
    private void installCrashLogger() {
        final Thread.UncaughtExceptionHandler prior = Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            @Override
            public void uncaughtException(Thread t, Throwable e) {
                try {
                    java.io.StringWriter sw = new java.io.StringWriter();
                    e.printStackTrace(new java.io.PrintWriter(sw));
                    Gdx.files.local("crash-log.txt").writeString(
                            "crash thread=" + t.getName() + "\n" + sw + "\n", true);
                } catch (Throwable ignored) {
                }
                if (prior != null) {
                    prior.uncaughtException(t, e);
                }
            }
        });
    }

    /** UI characters for the runtime FreeType bake, read from the asset that
     * tools/check_ui_font.py regenerates from the game sources. Falls back to
     * just the libGDX default ASCII set if the asset is ever missing. */
    private String uiChars() {
        try {
            return Gdx.files.internal("fonts/ui-chars.txt").readString("UTF-8")
                    .replace("\n", "").replace("\r", "");
        } catch (Throwable ignored) {
            return "";
        }
    }

    private BitmapFont loadFont(int size) {
        try {
            FreeTypeFontGenerator gen = new FreeTypeFontGenerator(Gdx.files.internal("fonts/NotoSansCJK-Sc.ttf"));
            FreeTypeFontGenerator.FreeTypeFontParameter p = new FreeTypeFontGenerator.FreeTypeFontParameter();
            p.size = size;
            p.color = Color.WHITE;
            p.borderWidth = 1.1f;
            p.borderColor = new Color(0f, 0f, 0f, 0.75f);
            // Characters = libGDX defaults (ASCII/latin) + the UI character set
            // generated by tools/check_ui_font.py into assets/fonts/ui-chars.txt.
            // It is derived from the actual UI strings every build, so newly added
            // text can never silently render as tofu again (the old hand-written
            // FONT_CHARS list + hand-subsetted TTF missed 足/·/， etc).
            p.characters = FreeTypeFontGenerator.DEFAULT_CHARS + uiChars();
            BitmapFont f = gen.generateFont(p);
            gen.dispose();
            return f;
        } catch (Exception ex) {
            Gdx.app.error("NanHaiVoyage", "font load failed", ex);
            BitmapFont fallback = new BitmapFont();
            fallback.getData().setScale(size / 16f);
            return fallback;
        }
    }

    @Override
    public void dispose() {
        if (getScreen() != null) {
            getScreen().hide();
        }
        if (skin != null) skin.dispose();
        if (font != null) font.dispose();
        if (fontSmall != null) fontSmall.dispose();
        if (batch != null) batch.dispose();
    }
}
